apiVersion: apps/v1
kind: Deployment
metadata: 
  name: devops-backend-deploy
  namespace: devops
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - devops-backend
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nodejs
          image: namankali/devops-backend:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - name: backend-port
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: devops-config
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: ACCESS_TOKEN_EXPIRES_IN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: JWT_EXPIRES_IN
            - name: ENCRYPTION_IV
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: ENCRYPTION_IV
            - name: ENCRYPTION_ALGO
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: ENCRYPTION_ALGO
            - name: ENCRYPTION_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: ENCRYPTION_SECRET
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: PGHOST
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: PGPASSWORD
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: PEPPER
            - name: SALT_ROUNDS
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: SALT_ROUNDS
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_TOKEN
            - name: GITHUB_TOKEN_ORG
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_TOKEN_ORG
            - name: GITHUB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_BASE_URL
            - name: GITHUB_ENCRYPTION_KEY_LENGTH
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_ENCRYPTION_KEY_LENGTH
            - name: GITHUB_ENCRYPTION_ALGO
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_ENCRYPTION_ALGO
            - name: GITHUB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_ENCRYPTION_KEY
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GITHUB_WEBHOOK_SECRET
          livenessProbe:
            httpGet:
              path: /api/index/health
              port: backend-port
            initialDelaySeconds: 10
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: devops-backend-service
  namespace: devops
spec:
  selector:
    app: devops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: backend-port
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-ingress
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: dev.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: devops-backend-service
                port:
                  number: 80
